//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSOAP.Ws_R {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="Ws_R.metodos_ws")]
    public interface metodos_ws {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/metodos_ws/nombre_propioRequest", ReplyAction="http://ws/metodos_ws/nombre_propioResponse")]
        ClienteSOAP.Ws_R.nombre_propioResponse nombre_propio(ClienteSOAP.Ws_R.nombre_propioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/metodos_ws/nombre_propioRequest", ReplyAction="http://ws/metodos_ws/nombre_propioResponse")]
        System.Threading.Tasks.Task<ClienteSOAP.Ws_R.nombre_propioResponse> nombre_propioAsync(ClienteSOAP.Ws_R.nombre_propioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/metodos_ws/val_digitoRequest", ReplyAction="http://ws/metodos_ws/val_digitoResponse")]
        ClienteSOAP.Ws_R.val_digitoResponse val_digito(ClienteSOAP.Ws_R.val_digitoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/metodos_ws/val_digitoRequest", ReplyAction="http://ws/metodos_ws/val_digitoResponse")]
        System.Threading.Tasks.Task<ClienteSOAP.Ws_R.val_digitoResponse> val_digitoAsync(ClienteSOAP.Ws_R.val_digitoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nombre_propioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nombre_propio", Namespace="http://ws/", Order=0)]
        public ClienteSOAP.Ws_R.nombre_propioRequestBody Body;
        
        public nombre_propioRequest() {
        }
        
        public nombre_propioRequest(ClienteSOAP.Ws_R.nombre_propioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class nombre_propioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string genero;
        
        public nombre_propioRequestBody() {
        }
        
        public nombre_propioRequestBody(string nombre, string genero) {
            this.nombre = nombre;
            this.genero = genero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nombre_propioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nombre_propioResponse", Namespace="http://ws/", Order=0)]
        public ClienteSOAP.Ws_R.nombre_propioResponseBody Body;
        
        public nombre_propioResponse() {
        }
        
        public nombre_propioResponse(ClienteSOAP.Ws_R.nombre_propioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class nombre_propioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public nombre_propioResponseBody() {
        }
        
        public nombre_propioResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class val_digitoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="val_digito", Namespace="http://ws/", Order=0)]
        public ClienteSOAP.Ws_R.val_digitoRequestBody Body;
        
        public val_digitoRequest() {
        }
        
        public val_digitoRequest(ClienteSOAP.Ws_R.val_digitoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class val_digitoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        public val_digitoRequestBody() {
        }
        
        public val_digitoRequestBody(string rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class val_digitoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="val_digitoResponse", Namespace="http://ws/", Order=0)]
        public ClienteSOAP.Ws_R.val_digitoResponseBody Body;
        
        public val_digitoResponse() {
        }
        
        public val_digitoResponse(ClienteSOAP.Ws_R.val_digitoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class val_digitoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public val_digitoResponseBody() {
        }
        
        public val_digitoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface metodos_wsChannel : ClienteSOAP.Ws_R.metodos_ws, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class metodos_wsClient : System.ServiceModel.ClientBase<ClienteSOAP.Ws_R.metodos_ws>, ClienteSOAP.Ws_R.metodos_ws {
        
        public metodos_wsClient() {
        }
        
        public metodos_wsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public metodos_wsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public metodos_wsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public metodos_wsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSOAP.Ws_R.nombre_propioResponse ClienteSOAP.Ws_R.metodos_ws.nombre_propio(ClienteSOAP.Ws_R.nombre_propioRequest request) {
            return base.Channel.nombre_propio(request);
        }
        
        public string nombre_propio(string nombre, string genero) {
            ClienteSOAP.Ws_R.nombre_propioRequest inValue = new ClienteSOAP.Ws_R.nombre_propioRequest();
            inValue.Body = new ClienteSOAP.Ws_R.nombre_propioRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.genero = genero;
            ClienteSOAP.Ws_R.nombre_propioResponse retVal = ((ClienteSOAP.Ws_R.metodos_ws)(this)).nombre_propio(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSOAP.Ws_R.nombre_propioResponse> ClienteSOAP.Ws_R.metodos_ws.nombre_propioAsync(ClienteSOAP.Ws_R.nombre_propioRequest request) {
            return base.Channel.nombre_propioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSOAP.Ws_R.nombre_propioResponse> nombre_propioAsync(string nombre, string genero) {
            ClienteSOAP.Ws_R.nombre_propioRequest inValue = new ClienteSOAP.Ws_R.nombre_propioRequest();
            inValue.Body = new ClienteSOAP.Ws_R.nombre_propioRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.genero = genero;
            return ((ClienteSOAP.Ws_R.metodos_ws)(this)).nombre_propioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSOAP.Ws_R.val_digitoResponse ClienteSOAP.Ws_R.metodos_ws.val_digito(ClienteSOAP.Ws_R.val_digitoRequest request) {
            return base.Channel.val_digito(request);
        }
        
        public string val_digito(string rut) {
            ClienteSOAP.Ws_R.val_digitoRequest inValue = new ClienteSOAP.Ws_R.val_digitoRequest();
            inValue.Body = new ClienteSOAP.Ws_R.val_digitoRequestBody();
            inValue.Body.rut = rut;
            ClienteSOAP.Ws_R.val_digitoResponse retVal = ((ClienteSOAP.Ws_R.metodos_ws)(this)).val_digito(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSOAP.Ws_R.val_digitoResponse> ClienteSOAP.Ws_R.metodos_ws.val_digitoAsync(ClienteSOAP.Ws_R.val_digitoRequest request) {
            return base.Channel.val_digitoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSOAP.Ws_R.val_digitoResponse> val_digitoAsync(string rut) {
            ClienteSOAP.Ws_R.val_digitoRequest inValue = new ClienteSOAP.Ws_R.val_digitoRequest();
            inValue.Body = new ClienteSOAP.Ws_R.val_digitoRequestBody();
            inValue.Body.rut = rut;
            return ((ClienteSOAP.Ws_R.metodos_ws)(this)).val_digitoAsync(inValue);
        }
    }
}
